notifications:
  email: false

language: generic
dist: xenial
services:
  - docker

branches:
  only:
    - master
    - /^\d\.\d$/

jobs:
  include:
    - stage: Unit tests
    - env: PHP=7.2 DEPS=low
    - stage: Code quality
      script:
        - make cs
        - make install phpunit-pull psalm

script:
  - if [[ ${DEPS} == low ]]; then make update-lowest; else make update; fi
  - make phpunit

cache:
  directories:
    - var/
