language: minimal

branches:
  only:
    - master
    - /^\d\.\d$/

jobs:
  include:
    - stage: Unit tests
    - env: DEPS=low
    - env: PHP=7.3
    - stage: Code quality
      script: make cs psalm

script:
  - if [[ ${DEPS} == low ]]; then make update-lowest; else make update; fi
  - make phpunit

cache:
  directories:
    - var/
